CREATE TABLE public.ch_zi1 (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               zi VARCHAR(255),
                               translation VARCHAR(255),
                               pinyin VARCHAR(255),
                               description VARCHAR(255),
                               example VARCHAR(255)
);

ALTER TABLE public.ch_zi1 OWNER TO postgres;