CREATE TABLE public.test_sessions (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      block_number INTEGER,
                                      score INTEGER,
                                      total_questions INTEGER,
                                      passed BOOLEAN NOT NULL,
                                      created_at TIMESTAMP WITHOUT TIME ZONE
);

ALTER TABLE public.test_sessions OWNER TO postgres;