
CREATE TABLE IF NOT EXISTS public.users (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            username VARCHAR(50) NOT NULL UNIQUE,
                                            password VARCHAR(255) NOT NULL,
                                            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


DO $$
    BEGIN
        EXECUTE 'ALTER TABLE public.users OWNER TO postgres';
    EXCEPTION WHEN others THEN

        NULL;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'test_sessions'
              AND column_name = 'user_id'
        ) THEN
            ALTER TABLE public.test_sessions ADD COLUMN user_id BIGINT;
        END IF;
    END $$;

DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM information_schema.table_constraints
            WHERE table_schema = 'public'
              AND table_name = 'test_sessions'
              AND constraint_name = 'fk_test_sessions_user'
        ) THEN
            ALTER TABLE public.test_sessions
                ADD CONSTRAINT fk_test_sessions_user
                    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
        END IF;
    END $$;